### ISSUE TITLE
No `secrets.yml.example` file

### ISSUE THREAD

**Issue by inooid** [NHLHogeschool/the-next-website#2]
I can't seem to get the project to work, because of missing rails secrets. It might be useful to add a `secrets.yml.example` file to show what keys are necessary to work.

So far I've found the `secret_key_base` and `google_calendar_id` keys, but I have no idea what good developer values could be.

Maybe @dirksierd has a working version of the `secrets.yml` file that he could share and by taking the sensitive data out I could turn it into a `secrets.yml.example` file.

**Comment by dirksierd** [comment]
there you go
